import os
from datetime import datetime
from flask import current_app
from app.extensions import db, mail
from app.models import Setting, User, Attendance, Worksheet, Holiday

from app.ai.gemini import generate_ceo_report
from flask_mail import Message
import pytz

IST = pytz.timezone("Asia/Kolkata")

def generate_pdf_file(content, date_str, output_path):
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib import colors
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable
    from reportlab.lib.units import cm

    doc = SimpleDocTemplate(
        output_path,
        pagesize=A4,
        rightMargin=2*cm,
        leftMargin=2*cm,
        topMargin=2*cm,
        bottomMargin=2*cm,
    )

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "title",
        parent=styles["Heading1"],
        fontSize=16,
        textColor=colors.HexColor("#1a1a2e"),
        spaceAfter=12,
    )
    body_style = ParagraphStyle(
        "body",
        parent=styles["Normal"],
        fontSize=10,
        leading=16,
        textColor=colors.HexColor("#333333"),
    )

    story = []
    story.append(Paragraph(f"Relay Daily Report — {date_str}", title_style))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#4f8ef7")))
    story.append(Spacer(1, 0.3*cm))

    for line in content.split("\n"):
        line = line.strip()
        if not line:
            story.append(Spacer(1, 0.2*cm))
        else:
            story.append(Paragraph(line.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;"), body_style))

    doc.build(story)


def compile_daily_report_job(app):
    """Background task to generate daily CEO reports and store them locally, with optional email delivery."""
    with app.app_context():
        today = datetime.now(IST).date()
        date_str = today.strftime("%Y-%m-%d")
        
        print(f"[{datetime.now(IST)}] Starting automated report generation for {date_str}...")
        
        # Ensure reports directory exists in project root
        reports_dir = os.path.join(os.path.dirname(app.root_path), "reports")
        os.makedirs(reports_dir, exist_ok=True)
        
        # Generate the report contents
        result = generate_ceo_report(today)
        if not result.get("success"):
            print(f"[{datetime.now(IST)}] Automated report failed: {result.get('message')}")
            return
            
        report_content = result.get("report")
        
        # Save TXT version
        txt_path = os.path.join(reports_dir, f"relay_report_{date_str}.txt")
        with open(txt_path, "w", encoding="utf-8") as f:
            f.write(report_content)
            
        # Save PDF version
        pdf_path = os.path.join(reports_dir, f"relay_report_{date_str}.pdf")
        try:
            generate_pdf_file(report_content, date_str, pdf_path)
            print(f"[{datetime.now(IST)}] Saved report files successfully in reports/")
        except Exception as e:
            print(f"[{datetime.now(IST)}] Error generating PDF: {str(e)}")
            pdf_path = None
            
        # Optional Email Delivery to Admin
        mail_username = app.config.get("MAIL_USERNAME")
        mail_password = app.config.get("MAIL_PASSWORD")
        
        if mail_username and mail_password:
            # Find the admin user(s) to email the report to
            admins = User.query.filter_by(role="admin", active=True).all()
            recipient_emails = [a.email for a in admins if a.email]
            
            if recipient_emails:
                try:
                    msg = Message(
                        subject=f"Relay Daily Summary Report — {today.strftime('%d/%m/%Y')}",
                        recipients=recipient_emails,
                        body=f"Hello,\n\nPlease find attached the automated daily summary report generated by Relay for {today.strftime('%d/%m/%Y')}.\n\nBest regards,\nRelay Automated Assistant"
                    )
                    
                    # Attach TXT
                    with open(txt_path, "r", encoding="utf-8") as f:
                        msg.attach(f"relay_report_{date_str}.txt", "text/plain", f.read())
                        
                    # Attach PDF
                    if pdf_path and os.path.exists(pdf_path):
                        with open(pdf_path, "rb") as f:
                            msg.attach(f"relay_report_{date_str}.pdf", "application/pdf", f.read())
                            
                    mail.send(msg)
                    print(f"[{datetime.now(IST)}] Daily report emailed successfully to {', '.join(recipient_emails)}.")
                except Exception as e:
                    print(f"[{datetime.now(IST)}] Failed to send automated report email: {str(e)}")
        else:
            print(f"[{datetime.now(IST)}] Skipping email: SMTP credentials not configured.")


def daily_db_backup_job(app):
    """Background task to create a daily database backup snapshot in backups/ folder."""
    with app.app_context():
        today_str = datetime.now(IST).strftime("%Y%m%d_%H%M%S")
        backups_dir = os.path.join(os.path.dirname(app.root_path), "backups")
        os.makedirs(backups_dir, exist_ok=True)

        db_uri = app.config.get("SQLALCHEMY_DATABASE_URI", "")
        if "sqlite" in db_uri:
            import shutil
            db_path = os.path.abspath(os.path.join(app.root_path, "..", "dev_relay.db"))
            if not os.path.exists(db_path):
                db_path = os.path.abspath(os.path.join(app.root_path, "..", "relay.db"))
            if os.path.exists(db_path):
                backup_target = os.path.join(backups_dir, f"relay_backup_{today_str}.db")
                shutil.copy2(db_path, backup_target)
                print(f"[{datetime.now(IST)}] Daily automated SQLite backup saved to {backup_target}")
                return

        # General JSON backup snapshot
        import json
        backup_data = {
            "timestamp": today_str,
            "users": [{"id": u.id, "employee_id": u.employee_id, "name": u.full_name, "email": u.email, "role": u.role, "section": u.section, "active": u.active, "joining_date": str(u.joining_date)} for u in User.query.all()],
            "attendance": [{"id": a.id, "user_id": a.user_id, "date": str(a.date), "status": a.status, "check_in": str(a.check_in), "check_out": str(a.check_out), "ip_address": a.ip_address} for a in Attendance.query.all()],
            "worksheets": [{"id": w.id, "user_id": w.user_id, "date": str(w.date), "content": w.content, "is_locked": w.is_locked} for w in Worksheet.query.all()],
        }
        json_path = os.path.join(backups_dir, f"relay_backup_{today_str}.json")
        with open(json_path, "w", encoding="utf-8") as f:
            json.dump(backup_data, f, indent=2)
        print(f"[{datetime.now(IST)}] Daily automated JSON backup saved to {json_path}")

