"""Add admin_unlocked to attendance

Revision ID: 9e61bc53c67a
Revises: 68944a85c368
Create Date: 2026-07-29 19:54:25.666037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e61bc53c67a'
down_revision = '68944a85c368'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_unlocked', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_column('admin_unlocked')

    # ### end Alembic commands ###
