"""holiday_day_type_color

Revision ID: c5a5e1c640bc
Revises: 005f2864bfdd
Create Date: 2026-08-03 15:39:08.765968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5a5e1c640bc'
down_revision = '005f2864bfdd'
branch_labels = None
depends_on = None


def upgrade():
    # Add columns with a server_default so existing rows get the default value
    with op.batch_alter_table('holidays', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'day_type', sa.String(length=30),
            nullable=False, server_default='Holiday'
        ))
        batch_op.add_column(sa.Column('color', sa.String(length=10), nullable=True))



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('holidays', schema=None) as batch_op:
        batch_op.drop_column('color')
        batch_op.drop_column('day_type')

    # ### end Alembic commands ###
